### ISSUE TITLE
Не використовуй інлайн функції

### ISSUE THREAD

**Issue by Maksym1910** [VikaAbysova/react-courses-app#6]
https://github.com/VikaAbysova/react-courses-app/blob/8d6435d51e3fe10c9ea5b2fc8e5676dbd2857249/src/components/Login/Login.jsx#L60

**Comment by Maksym1910** [comment]
По всьому проекту потрібно прибрати використання інлайн функцій

**Comment by VikaAbysova** [comment]
Прибрала всюди, залила в 5 пулі.
