### ISSUE TITLE
змінна BASE_URL

### ISSUE THREAD

**Issue by Maksym1910** [VikaAbysova/react-courses-app#8]
https://github.com/VikaAbysova/react-courses-app/blob/8d6435d51e3fe10c9ea5b2fc8e5676dbd2857249/src/store/services.js#L2

Створи нову змінну `BASE_URL` яка міститиме базовий домен, у твоєму випадку локалхост

**Comment by Maksym1910** [comment]
Також файл `services.js` загалом винеси в окремий модуль/папку типу `api`

**Comment by VikaAbysova** [comment]
зміни залила
